ALTER TABLE "CrmConfig" ADD COLUMN IF NOT EXISTS "clientId" TEXT;
ALTER TABLE "CrmConfig" ADD COLUMN IF NOT EXISTS "clientSecret" TEXT;
ALTER TABLE "CrmConfig" ADD COLUMN IF NOT EXISTS "refreshToken" TEXT;
ALTER TABLE "CrmConfig" ADD COLUMN IF NOT EXISTS "tokenExpiresAt" TIMESTAMP(3);
